### ISSUE TITLE
split_seqs() fails on color number > 15

### ISSUE THREAD

**Issue by gmelchett** [jquast/blessed#101]
I recently noticed that split_seq() fails on color > 15. Example:
```
>>> t = blessed.Terminal()
>>> t.split_seqs(t.color(15))
['\x1b[97m']
>>> t.split_seqs(t.color(16))
['\x1b[38;5;16m', '16']
>>>
```
I would expect that the later would be:
```
['\x1b[38;5;16m']
```

**Comment by jquast** [comment]
is `t.number_of_colors` 16 or 256?

**Comment by gmelchett** [comment]
>>> t.number_of_colors
256
>>>

**Comment by avylove** [comment]
@jquast The problem seems to be `'color256'` in `_capabilities.CAPABILITIES_ADDITIVES` has parenthesis around `\d+`, so it's matching on both the whole sequence and the number. Are the parentheses needed there?

```python
>>> t = blessed.Terminal()
>>> t.caps['color256'].pattern
'\\\x1b\\[38;5;(\\d+)m'

>>> filter(None, re.split('({0})'.format(t.caps['color256'].pattern), t.color(16)))
[u'\x1b[38;5;16m', u'16']
>>> filter(None, re.split('({0})'.format('\\\x1b\\[38;5;\\d+m'), t.color(16)))
[u'\x1b[38;5;16m']

```

**Comment by jquast** [comment]
thanks @avylove I've added to changelog
