### ISSUE TITLE
Store/restore terminal settings

### ISSUE THREAD

**Issue by wintersteiger** [jquast/blessed#103]
I'd like to save the current terminal settings (mainly colors, bold, blink) so I can later restore the same settings at another screen location. Is that at all possible and does blessed provide a way to do that?

**Comment by jquast** [comment]
in a way, yes, it does. all terminals support save an restore of cursor position. many terminal emulators also interpreter this to mean "restore attributes". It is a special sequence, which blessed helps you print. so you are welcome to experiment. This is the `save cursor` and `restore cursor` sequence, which the `location` context manager helps you use: http://blessed.readthedocs.io/en/latest/api.html#blessed.terminal.Terminal.location

You can also do some tricks with the secondary screen, http://blessed.readthedocs.io/en/latest/api.html#blessed.terminal.Terminal.fullscreen

and most recently, find out the cursor position, not just "save" to middle-layer an restore: http://blessed.readthedocs.io/en/latest/api.html#blessed.terminal.Terminal.get_location

I think what you would rather have, is a nice keyword dictionary hash of attributes, like current screen position and color, in nice structure data. I'm afraid that's not available to you, I think the ncurses C library has a global variable that defines these attributes, under the structure pointed to by global variable `curterm`. but these are not available to use.

This context manager, `location()`, maybe could use a docstring to mention your findings, if it is known to restore attributes also, thanks!
