### ISSUE TITLE
Example for forms?

### ISSUE THREAD

**Issue by gamesbook** [jquast/blessed#105]
Is there perhaps an example of showing how blessed could be used to allow a user to "fill in" (add/edit) data in a form-like display i.e. label + designated area to type in data and then access that data for further processing.  Thanks!

**Comment by jquast** [comment]
I have only one example of my own, but feel free to search GitHub, people have made this with blessed a few times. UI is tricky, UI libraries often impose some kind of asynchronous framework or event loop management.

Anyway, my own version was for a “BBS”, which, although it used blessed, had an extra layer of abstraction you’ll have to mess with to make it a pure blessed-only project,

https://github.com/jquast/x84/blob/master/x84/bbs/editor.py

Best wishes and have lots of fun!!
jq
