### ISSUE TITLE
curses.has_key._capability_names missing on systems without native _curses.has_key

### ISSUE THREAD

**Issue by Kaedenn** [jquast/blessed#111]
I've downloaded Blessed 1.15.0 on the `HP-UX-B.11.31-ia64-32bit` build of Python 2.7.13. The following code generates the following traceback:

```
>>> from blessed import Terminal
>>> term = Terminal()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/self/.local/lib/python2.7/site-packages/blessed/terminal.py", line 229, in __init__
    self.__init__keycodes()
  File "/home/self/.local/lib/python2.7/site-packages/blessed/terminal.py", line 277, in __init__keycodes
    self._keymap = get_keyboard_sequences(self)
  File "/home/self/.local/lib/python2.7/site-packages/blessed/keyboard.py", line 174, in get_keyboard_sequences
    capability_names = curses.has_key._capability_names
AttributeError: 'function' object has no attribute '_capability_names'
```

The object `curses.has_key` is a `function` with only the usual attributes; no single-underscore attributes are present.

I believe the problem is caused by my `_curses` module not exporting the `has_key` function, and therefore exports the `curses.has_key.has_key` function instead. Because the module and function have the same name, the `has_key` module is not accessible. The following is from my `curses/__init__.py`:

```python
# Import Python has_key() implementation if _curses doesn't contain has_key()

try:
    has_key
except NameError:
    from has_key import has_key
```

Because `has_key.has_key` is a function, this makes `has_key._capability_names` inaccessible.

**Comment by Kaedenn** [comment]
Suggested workaround:

In `keyboard.py`, instead of `capability_names = curses.has_key._capability_names`, we have the following code:

```python
try:
  capability_names = curses.has_key._capability_names
except AttributeError as _:
  from curses.has_key import _capability_names as capability_names
```
and replace all references to

**Comment by Kaedenn** [comment]
A simple test case would be to provide a `_curses.py` module which exports everything from the native `_curses` module except for `has_key`, and letting `curses/__init__.py` react accordingly. Then, construct `term = blessed.Terminal()` and ensure no exception is raised.

**Comment by avylove** [comment]
So `from curses.has_key import _capability_names as capability_names` works on your system? If it does, moving that to the top of the file with the other imports would probably be sufficient. I actually have something similar in an existing pull request.

**Comment by Kaedenn** [comment]
Yes, that line works correctly on my system.

**Comment by avylove** [comment]
@jquast Sounds like we can use the logic in #110 `blessed/keyboard.py` (minus the platform test) and `blessed/tests/test_keyboard.py` to fix this universally. It's basically moving the import to the top of the file and fixing up a monkeypatch in the tests.

**Comment by jquast** [comment]
Sounds fine to me! Pr’s welcome but that’s definitely he way to go thanks all for lithe investigation

**Comment by avylove** [comment]
@Kaedenn is this working now with 1.16.0?

**Comment by jquast** [comment]
we use the code pattern you suggest, so i suggest this is resolved
