### ISSUE TITLE
Include 3rd party apps & screenshots in docs/examples.rst

### ISSUE THREAD

**Issue by jquast** [jquast/blessed#113]
there are a lot of lovely apps made with blessed, showing screenshots and links would help developers find example source code and understand what the library is for

- [x] https://github.com/snare/voltron
- [x] https://github.com/thisisparker/cursewords
- [x] https://github.com/AmmsA/Githeat
- [ ] https://github.com/bisoncorps/search-engine-parser
- [x] https://github.com/FedericoCeratto/dashing
- [x] https://github.com/Rockhopper-Technologies/enlighten
- [ ] https://github.com/owlowlgo/redterm
- [ ] https://github.com/justaboredkid/sacred-tui
- [ ] https://github.com/polisflatt/speedfetch
- [x] https://github.com/wookayin/gpustat
- [ ] https://github.com/10gic/yatg
- [ ] https://github.com/vitkyrka/xalc
- [ ] https://github.com/drmikehenry/ptee
- [x] https://github.com/rolfmorel/macht

**Comment by jquast** [comment]
and there were 3 "mini games" in this old gist of mine, https://gist.github.com/jquast/7018509
and i think there is a tetris out there ..

**Comment by avylove** [comment]
This looks great!
