### ISSUE TITLE
Backspace is mapped to Delete

### ISSUE THREAD

**Issue by jwezel** [jquast/blessed#114]
The Backspace key is wrongly reported as Delete, as I was able to confirm:

```
>> print(blessed.terminal.get_keyboard_sequences(myterm))
..., ('\x7f', 330), ...
```
Instead of 330 it should be 263.

**Comment by jwezel** [comment]
Created a PR for this.

**Comment by avylove** [comment]
I'm not sure what's happening here. If you look at a standard [ascii table](http://www.asciitable.com/), 7f (127) is delete, which is keycode 330. However, you're right, when you run [keymatrix.py](https://github.com/jquast/blessed/blob/master/bin/keymatrix.py), backspace is coming up as ``\x7f``. I'm pretty certain that was not the case in the past, so I wonder if something has changed. I'm using Fedora 31. What OS and version are you running?

**Comment by avylove** [comment]
One other interesting thing is ctrl + backspace provides ``\x08`` on my system.

**Comment by jwezel** [comment]
I'm running Ubuntu 18.04.

I think backspace has always been 127 from the start, maybe it was wrongly assigned in the past.

**Comment by avylove** [comment]
Doing some research, it seems it's either 127 or 8 depending on the system configuration, though it seems 127 is more common with delete sending ``\x1b[3~``. If it's more common, it probably makes sense to change it, but that's something @jquast will have to weigh in on.

**Comment by jquast** [comment]
I am ok with 127 becoming backspace, whatever is most usual for today.

As for "from the start", 127 is a 7-bit punchout of teletype tape, literally go back and punch it all out. stty, "backspace is delete", and getting the '?' character when you try to correct a mistake was a great unix tradition, whatever mac, linux, and windows generally settled upon is what we'll go with, we'll roll into the next release thanks
