### ISSUE TITLE
Some tests fail on Windows pytest, but succeed in interactive python

### ISSUE THREAD

**Issue by jquast** [jquast/blessed#122]
*Problem*: Some automatic tests fail to determine printable lengths of strings on Windows, but, does not have any trouble when executing the code outside of pytest.

Some tests, which measure the printable length of strings, fail to correctly match terminal sequences of its own making. For example, the result of `term.length('_' + term.move_left)` should be a `0`, because of left movement of carriage.

But, when executing those same lines of code directly in python.exe or IPython, do not reproduce! Furthermore, using ``tox -e py38 -- -k test_name``, to ensure side-effects of other tests are not causing problems in these tests, has no effect, they continue to fail.

Disabling such tests with `pytest.markif` with this issue number

**Comment by jquast** [comment]
Some of them use `TestTerminal`, which uses a an *IOStream* rather than sys.stdin's file descriptor, maybe related

**Comment by avylove** [comment]
Looks like `force_styling=True` is needed. In that particular test, the stream is not specified which causes it to use sys.`__stdout__`  and ` isatty()` returns false under pytest.

I think goes back to the lack of PTY support on Windows. Some projects use [winpty](https://github.com/rprichard/winpty) via [pywinpty](https://pypi.org/project/pywinpty). Last year Microsoft rolled out [ConPTY](https://devblogs.microsoft.com/commandline/windows-command-line-introducing-the-windows-pseudo-console-conpty/) on [Windows 10 1809+ and Windows Server 2019](https://docs.microsoft.com/en-us/windows/console/createpseudoconsole#requirements). Some projects, like VSCode, seem to have started using it, but I haven't see much [movement in the Python space](https://github.com/microsoft/terminal/issues/311).

Anyway, until we have a good pty substitute for Windows, `force_styling=True` will work. Not sure how you want to implement that, so I'll leave it to you.

**Comment by jquast** [comment]
Closing by #127
