### ISSUE TITLE
Terminal.color() returns wrong sequence on direct/indirect color terminals

### ISSUE THREAD

**Issue by avylove** [jquast/blessed#139]
Looking at [terminfo.src](url), there are three definitions for 24-bit color:
- xterm+indirect
- xterm+direct
- xterm+direct2

These are used in these terminals:
- xterm-indirect
- konsole-direct
- st-direct
- vte-direct
- nsterm-direct
- alacritty-direct
- vscode-direct
- xterm-direct
- iterm2-direct
- mlterm-direct
- mintty-direct
- xterm-direct2
- kitty-direct

All 3 definitions use RGB color for setab and setaf unless the first parameter is less than 8, otherwise it's considered an RBG color in 1 byte chunks. While this seems like a bug since an RGB color like (0,0,7) would result in `b'\x1b[37m'`, our main issue is `Terminal.color()` will return the wrong color for any color above 7.

    import blessed
    term = blessed.Terminal(kind='xterm-direct')
    term.color(200)
    # '\x1b[38:2::0:0:200m'

**Comment by avylove** [comment]
If we want to maintain compatibility across terminal types, we'll have to detect these terminals and for `Terminal.color()`, use `RGB_256TABLE` to convert the values to RGB values.

We can do a test in `Terminal__init__color_capabilities()` similar to:
        self._direct_color = re.search(r'0[:;]0[:;]50m$', term._foreground_color(50))

**Comment by avylove** [comment]
Another issue is the format for xterm+direct and xterm+direct2 is a little different than what we have for RGB color, using colons instead of semicolons. `\x1b[38:2::0:0:15m`, `\x1b[38:2:0:0:15m`

I think what we have will work, but I'm not sure how to test it. If it wasn't for the bug with values less than 8, I would think we could use setab/setaf to output RGB colors for these direct color terminals. We can wait and see if this becomes an issue, or we can remove `%?%p1%{8}%<%t4%p1%d%e` and `%?%p1%{8}%<%t3%p1%d%e` from setab and aetaf on detected terminals to create rgb capability mixins, defaulting to what we already have.

**Comment by avylove** [comment]
Since `color() `is a property and returns a `ParameterizingString`, I'm not sure how much we can do except suggest downstream developers use X11 named colors rather than numbers in the 256 color palette.

**Comment by jquast** [comment]
Suggesting never to use the 256-color index is what I've done in the documentation I'll be proposing later today.
