### ISSUE TITLE
Check for deadlinks

### ISSUE THREAD

**Issue by jquast** [jquast/blessed#149]
- Need tox to check for deadlinks (sphinx has a special link_check builder for this)

Problem: Awaiting readthedocs.org builds, i'm not sure why the "stable" version is pointing to several releases ago, which is what all the hard-coded links are now dead-linked to :( anyway found this out by hand, need to tool it check them all

**Comment by avylove** [comment]
Apparently that was a bug, which they said was fixed, but may require wiping the environment and rebuilding. Checking for dead links is probably a good idea anyway.

https://github.com/readthedocs/readthedocs.org/issues/2032
https://github.com/readthedocs/readthedocs.org/pull/3913

**Comment by jquast** [comment]
Thanks for looking into it, I purged/rebuilt and fixed the stable release on sphinx, anyway
