### ISSUE TITLE
t.hidden_cursor() context manager broken

### ISSUE THREAD

**Issue by whweasel** [jquast/blessed#151]
I am using Windows 10, it used to work in the past, but the t.hidden_cursor() context manager doesn't even do anything anymore

**Comment by jquast** [comment]
I'm sorry you're having trouble. I loaded up Windows 10, used pip to install the latest version of blessed and IPython, and tested ``hidden_cursor()`` which worked successfully.

<img width="991" alt="Screen Shot 2020-02-08 at 8 58 19 AM" src="https://user-images.githubusercontent.com/972584/74088992-29a97800-4a51-11ea-825b-9fed5922170e.png">
