### ISSUE TITLE
raw() and inkey() slow down over time

### ISSUE THREAD

**Issue by whweasel** [jquast/blessed#153]
the more i use these functions, the longer it takes to perform a key timeout. I set the timeout for inkey() as 1 millisecond, but instead, the timeout is 100 milliseconds, inside a for loop. I suspect there is a memory issue here.

**Comment by avylove** [comment]
Can you provide the OS and Python version you're using as well as some code that demonstrates the issue?

**Comment by whweasel** [comment]
Actually, THE ISSUE HAS BEEN SOLVED.

I was right about it being a memory issue. It was solved with a simple garbage collect. It seems that memory gets built up whenever inkey() is called, and so it just clogs up the timeout until a manual garbage collect happens. The thing here is that the garbage seems to build up, even after the script is finished.

So here is a tip for everyone here. Do a simple import gc, and then call the cg.collect() at the beginning, or end, of each code segment, if you code that way (I see you, former Java and C++ people... hehe). If not, just do an occasional gc.collect throughout your code. Like this:

```py
import gc
gc.collect()
```

**Comment by jquast** [comment]
We have examples that use 1ms timing, such as plasma.py, https://github.com/jquast/blessed/blob/master/bin/plasma.py#L109

I have never seen any kind of performance or memory leak issue, if there is such an issue, we would want to fix it, or document it for others, I don't think your problem can relate, but I appreciate the thought

**Comment by whweasel** [comment]
> We have examples that use 1ms timing, such as plasma.py, https://github.com/jquast/blessed/blob/master/bin/plasma.py#L109
> 
> I have never seen any kind of performance or memory leak issue, if there is such an issue, we would want to fix it, or document it for others, I don't think your problem can relate, but I appreciate the thought

The issue is back, and there seems to be no way to shoot it down. I guess I could compare it to trying to use an antivirus to get rid of adware, when I really have a hijacked hosts file... anyway, i put the project on github > https://github.com/whweasel/thing, i can't figure out what is going on here without understanding exactly how raw(), cbreak(), and inkey() work on a low-level

**Comment by avylove** [comment]
Is this still an issue? If so, can you provide an independent code snippet which demonstrates the problem?
