### ISSUE TITLE
Delay with escape key

### ISSUE THREAD

**Issue by whweasel** [jquast/blessed#156]
There is a two second delay between pressing the escape key, and the return of inkey() and raw(). Check this too, (https://stackoverflow.com/questions/27372068/why-does-the-escape-key-have-a-delay-in-python-curses), I believe curses is a dependency of Blessed.

**Comment by jquast** [comment]
It is not 2 seconds, it is *0.35* seconds. And yes, this is true, expected, and documented. 

From https://blessed.readthedocs.io/en/latest/api/terminal.html#blessed.terminal.Terminal.inkey

> esc_delay (float) – To distinguish between the keystroke of KEY_ESCAPE, and sequences beginning with escape, the parameter esc_delay specifies the amount of time after receiving escape (chr(27)) to seek for the completion of an application key before returning a Keystroke instance for KEY_ESCAPE.
