### ISSUE TITLE
Failing tests with COLORTERM=truecolor or COLORTERM=24bit

### ISSUE THREAD

**Issue by sbraz** [jquast/blessed#162]
Hi again,
It took me a long time to find out why two tests were failing for me.
Apparently this is because of this line:
https://github.com/jquast/blessed/blob/39bdd9cfbd0948ddc4ac26372836cdeb871420b4/blessed/terminal.py#L267
It's quite easy to reproduce:
```
COLORTERM=truecolor pytest -vv tests/test_core.py::test_number_of_colors_without_tty tests/test_core.py::test_number_of_colors_with_tty
```
will make both tests fail because of `AssertionError: assert 16777216 == 0`.

It is no problem for me to force an empty `COLORTERM` while running tests but maybe this can be fixed. It looks like `truecolor` is a default for [all vte-based terminals](https://github.com/GNOME/vte/blob/344c2e77e9fdbc19f4c213c23b7bf91e93a9f7aa/src/pty.cc#L322) and for [Konsole](https://github.com/KDE/konsole/blob/028a31edda4a6c71dcc7f6d4eff15565f6ad32a5/src/Profile.cpp#L167).

**Comment by jquast** [comment]
The tests are executed through tox which ensures a reproducible environment. Tox would never pass ``COLORTERM``, and you should not, either.

**Comment by Arfrever** [comment]
But what about very likely situation, in which user himself/herself does not set `COLORTERM=truecolor`, but this variable is automatically implicitly set by terminal application?

**Comment by jquast** [comment]
The code works exactly as defined, please review more carefully what I am telling you.

https://blessed.readthedocs.io/en/latest/project.html#running-tests
https://tox.readthedocs.io/en/latest/example/basic.html#passing-down-environment-variables

There are hundreds of possible environment variable definitions that could cause any test to fail for any reason, defensively writing code in my tests is a solution that will never converge.

The solution is reproducible test environments as provided by tox, if you don’t want to to run tox, you will have to do everything that tox does yourself—most notably to clear all environment variables except PATH.

**Comment by avylove** [comment]
@Arfrever if a terminal application sets COLORTERM incorrectly, that would be a bug in that application. The COLORTERM variable is intended to signal to other programs whether the terminal is 24-bit color capable. In general use, Blessed will determine how to interpret color requests based on what the environment tells it about the terminal. The tests mock various environments that may be encountered, and expect to be running in a sanitized environment, like that provided by tox.

**Comment by Arfrever** [comment]
And if my terminal **is** 24-bit capable?

**Comment by jquast** [comment]
This discussion is closed, I would kindly request that gentoo not include blessed, or, to provide a different ambassador to open any further issues
