### ISSUE TITLE
Release 1.17.6 on pypi contains docs/_build directory and at least one __pycache__ directory

### ISSUE THREAD

**Issue by P-EB** [jquast/blessed#169]
Dear @jquast 

The release you've made of blessed 1.17.6 on pypi does contain the _build directory in docs/ and some __pycache__ directories, too (eg in docs/sphinxext).

For the Debian release, I've repacked the tarball without these additional directories, but I thought it might be worth notifying you.

Cheers!

**Comment by jquast** [comment]
thanks, i'll try to fix it, this was @sbraz's change from #161 causing me grief again

**Comment by P-EB** [comment]
@jquast thanks a lot. I don't know if pypi allows reuploads, if not, don't bother, I can manage the work for this release. :)

Cheers!

**Comment by P-EB** [comment]
Btw, I do indeed like being able to provide the documentation compiled in HTML along with the package. I tend to go on the official documentation when working with FOSS, but sometimes I don't have an internet connection, and the compiled doc provided with the package is a nice feature.

That's why I actually compile and release the doc of blessed in python-blessed on Debian.

Thanks for providing these rst files!

**Comment by sbraz** [comment]
@jquast I can look into making a PR for that, probably using `global-exclude`.

**Comment by ofek** [comment]
Any progress on this?

**Comment by jquast** [comment]
We're just waiting for someone to make the change and do the testing and submit the PR, I will get to it when I have the time to volunteer, but it is a Sunday and it is Dinner time. You are welcome to help move this issue forward by making a submission with your github account.

I just published https://jeffquast.com/post/terminal_wcwidth_solution/ which I felt was more important, that is why I spent the whole day on it, for example.

**Comment by sbraz** [comment]
I haven't found the right options to not include the `docs/_build` folder. I'll _try_ to work on it this week.

**Comment by ofek** [comment]
https://packaging.python.org/guides/using-manifest-in/#manifest-in-commands

```
prune docs/_build
global-exclude *.py[cod] __pycache__
```

**Comment by jquast** [comment]
addressed by 1.17.8 in #173, released to pypi
