### ISSUE TITLE
Numpad input not recognised 

### ISSUE THREAD

**Issue by spacebiggles** [jquast/blessed#17]
Hi. Have been using this to write a roguelike. Today when implementing diagonal movement, I found that I couldn't get term.KEY_LL and the such from the numpad. The upper right key is recognised as KEY_PGUP. It thinks that the 7 is KEY_ESC and seems to fail to read it as a sequence, producing multiple inputs. According to this http://stackoverflow.com/questions/16975367/ncurses-reading-numpad-keys-and-escaping, crawl hacks around it. Is there a way blessed can do similar? I had a go at monkey patching but it didn't go well.

**Comment by jquast** [comment]
strange thing i found today in SyncTerm, was that its F5 key is mistaken for KEY_KP_4 !?

filed #43
