### ISSUE TITLE
Pipe input to python script and later be able to read user input with inkey

### ISSUE THREAD

**Issue by MasterMedo** [jquast/blessed#182]
If I were to do `cat tmp | python program.py` is there a way to reset the input stream for blessed so the program becomes interactive?
Something like:

```python
term.stdin.close()
term.stdin = os.fdopen(0)
```

**Comment by MasterMedo** [comment]
Nevermind, found what you're using in the source. `sys.__stdin__ = os.fdopen(1)` does the trick.

**Comment by jquast** [comment]
Glad to help :) have fun
