### ISSUE TITLE
type hints?

### ISSUE THREAD

**Issue by dlax** [jquast/blessed#190]
It'd be nice to add type hints [PEP 484](https://www.python.org/dev/peps/pep-0484/) in blessed code base and then distribute them (following [PEP 561](https://www.python.org/dev/peps/pep-0561/)).

Is there any interest in this? (or any objection)

Since the library still supports Python 2, we'll need to write type annotations as stub files (`.pyi`).

I'd be happy to start working on this.

**Comment by jquast** [comment]
No objection, and thank you for your consideration for retaining backwards compatibility.

- I hope you recognize that there may be little benefit to downstream developers, which mainly call into the class's magic ``__getattr__`` method, https://github.com/jquast/blessed/blob/master/blessed/terminal.py#L343-L375 I don't expect type hinting to work?
- And may be difficult to annotate, such as the metaclassing of``__new__`` and ``__call__`` methods in `blessed.formatters`.

So I'm not particularly eager for it, but if the type annotations are well accurate and it passes tests for these older platforms, I would merge it.

**Comment by dlax** [comment]
>  * I hope you recognize that there may be little benefit to downstream developers, which mainly call into the class's magic `__getattr__` method, https://github.com/jquast/blessed/blob/master/blessed/terminal.py#L343-L375 I don't expect type hinting to work?
>  * And may be difficult to annotate, such as the metaclassing of`__new__` and `__call__` methods in `blessed.formatters`.

The `__call__` part is indeed a bit tricky. I made it work by ensuring that all formatters declare the same interface `Callable[[Union[int, str]], ...]` despite some of them only accept either `int` or `str`.

Out of curiosity (it doesn't matter here), is support for python 2.6 still desirable?

**Comment by jquast** [comment]
I think we decided python 2.6 is no longer supported/tested, thanks
