### ISSUE TITLE
PowerShell and cmd Prompt Not Showing Colors

### ISSUE THREAD

**Issue by MrHemlock** [jquast/blessed#194]
Having a rather odd issue with the library.  For some reason I'm unable to see all the colors that blessed has to offer.  I ran the example code `x11_colorpicker.py` and only about half a dozen colors properly displayed.  Is there something I'm missing?

**Comment by avylove** [comment]
What version of Windows are you running? The number of colors is handled by the Jinxed library on Windows. If you're running an older version of Windows, only 16 colors is supported. Blessed will downscale colors beyond that range to the supported range.

**Comment by MrHemlock** [comment]
Windows 10 Professional 64-bit

**Comment by avylove** [comment]
Can you run this and let me know what you get?

```
>>> import platform
>>> platform.version()

>>> import os
>>> os.environ.get('ANSICON')
```

**Comment by MrHemlock** [comment]
`platform.version()` gave me `10.0.19041`
`os.environ.get('ANSICON')` gave me no output.

**Comment by avylove** [comment]
Then you should be able to support 16-bit color. I can't reproduce your issue with Python 3.9 on Windows 10.0.19041.

Can you try the following?
```
>>> import blessed
>>> term = blessed.Terminal()
>>> term._kind
'vtwin10'
>>> term.errors
['parameters: kind=None, stream=None, force_styling=False']
>>> term.does_styling
True
>>> term.number_of_colors
16777216
```

**Comment by MrHemlock** [comment]
Got the exact same output as you did:
```py
In [1]: import blessed

In [2]: term = blessed. Terminal()

In [3]: term
Out[3]: <blessed.win_terminal.Terminal at 0x1dc27d4dac0>

In [4]: term._kind
Out[4]: 'vtwin10'

In [5]: term.errors
Out[5]: ['parameters: kind=None, stream=None, force_styling=False']

In [6]: term.does_styling
Out[6]: True

In [7]: term.number_of_colors
Out[7]: 16777216
```
Here's some example screenshots.  Some colors work, a majority don't.  (not sure if these help, but I figured it couldn't hurt to show you.)
![2021-02-22 15_47_07-Window](https://user-images.githubusercontent.com/26422638/108774966-08191280-7526-11eb-977f-84cab0322b8d.png)
![2021-02-22 15_47_50-Window](https://user-images.githubusercontent.com/26422638/108774967-08b1a900-7526-11eb-90ca-41d1faf14c75.png)
![2021-02-22 15_48_21-Window](https://user-images.githubusercontent.com/26422638/108774970-08b1a900-7526-11eb-8932-d7546a9a2231.png)

**Comment by avylove** [comment]
It seems you are using `ipython` rather than `python` to run the commands. I get the same results on Windows with `ipython`. While it's not the intended interpreter, it does work on Linux. That said, IPython does a lot of its own terminal manipulation and it may be difficult to determine what it's doing. If you need IPython to work in this way, it may be worth filing a bug with them.

**Comment by MrHemlock** [comment]
Fair enough.  The only reason I was attempting to use `ipython` was because that was what the example gif used in the introduction section on the README.rst
