### ISSUE TITLE
blessed.Terminal().<color>("str") not working properly

### ISSUE THREAD

**Issue by Apocryphon-X** [jquast/blessed#200]
I just installed blessed via PyPi using `pip3 install blessed`. When i tried to test the library with some colors from the [docs](https://blessed.readthedocs.io/en/latest/colors.html) this happened:

![Demo_Blessed](https://user-images.githubusercontent.com/40130428/111596557-e876b200-8792-11eb-8711-ce479b7af83e.gif)

Also, when i print the `Terminal().orangered` value, it doesnt show anything at all:
![Demo_Blessed2](https://user-images.githubusercontent.com/40130428/111597856-3dff8e80-8794-11eb-8a60-19e7d45087af.gif)

This happens with every color out of the 16 Colors group. I dont know if i installed the library in the wrong way or maybe im missing something. 

# Environment
- Ubuntu 20.04 (On WSL 1).
- Microsoft Windows 10 Home Single Language 10.0.18363 Compilation 18363.

**Comment by avylove** [comment]
Sorry you're having issues. These animations aren't as helpful as standard text. Please provide the following:

```
>>> blessed.__version__
'1.17.12'
>>> term._kind
'vtwin10'
>>> term.errors
['parameters: kind=None, stream=None, force_styling=False']
>>> term.does_styling
True
```

**Comment by Apocryphon-X** [comment]
Oh right, sorry about the inconvinience with the animations. Here is the info:

```
>>> blessed.__version__
'1.15.0'
>>> term._kind
'xterm-256color'
>>> term.errors
''
>>> term.does_styling
True
```

**Comment by Apocryphon-X** [comment]
Issue fixed by my side, i just notice that `pip3 install blessed` installed the version 1.15.0. I dont know why it happened but after reinstalling the lib it worked perfectly fine. Thank you so much for the feedback!

**Comment by avylove** [comment]
Glad it's working now!
