### ISSUE TITLE
Feature Request: FormattingString aware clamp function

### ISSUE THREAD

**Issue by fishermans-friend** [jquast/blessed#211]
One of the more common issues I run into is what to do when I want to display something, but there's no space left on the screen/line.

There are several ways to solve this, of course, but one of the options I choose sometimes is to simply clamp the text when there's no space and instead just display as much as possible, e.g.

```python
from blessed import Terminal

term = Terminal()
text = "Here's some long text which I want to clamp if it's too long to fit on the line, rather than go to a new line."
text = text[:term.width]
print(text)
```

This works fine for plain text, but the issue comes if you want to use formatting strings on the text.

```python
from blessed import Terminal

term = Terminal()
text = f"{term.red}Here's {term.orange}some {term.yellow}coloured {term.green}text{term.normal}"
text = text[:term.width]  # This uses the character count rather than the sequence aware length
print(text)  # Does not work properly
```

For this, I propose a function in the same vein as the `Terminal.wrap()`, `Terminal.center()`, `Terminal.ljust()`, etc. A `Terminal.clamp()` (or some other name) function, which does the needful in cutting down only the amount of printable characters needed, without touching the formatting characters.

One possible implementation may be something like this:

```python
from blessed import Terminal
from blessed.sequences import iter_parse
from wcwidth import wcwidth

def clamp(string: str, length: int) -> str:
    """
    Clamp the given string to the displayed length in a formatting-aware fashion. Format string
    sequences are not touched, and only the printable characters are removed to reach the
    desired length.

    :param string: A string to clamp.
    :param length: The desired display length of the string.
    :return: The string cut down to at most ``length`` printable characters.
    """
    term = Terminal()
    output = ""
    lenny = 0
    for text, cap in iter_parse(term, string):
        if not cap:
            width = wcwidth(text)
            lenny += width
            if lenny <= length:
                output += text
            continue
        output += text
    return output
```

But I'm sure smarter people than me can come up with a more efficient way of doing it.

**Comment by avylove** [comment]
Thanks submitting this! It seems like a good idea to me, but I'd call it `truncate()`. The approach you took is generally fine, but it should probably be a method on `blessed.sequences.Sequence` rather than stand alone.

**Comment by fishermans-friend** [comment]
Change was merged, closing.
