### ISSUE TITLE
Interest in get_fgcolor() and get_bgcolor()?

### ISSUE THREAD

**Issue by stefanholek** [jquast/blessed#238]
Is the blessed project interested in including get_fgcolor() and get_bgcolor()?

The functions work exactly like get_location(), but instead of DSR 6 they emit OSC 10 & 11.[^1]

## Pro
Together with a luminance[^2] function, get_fgcolor() and get_bgcolor() could be used to tell light mode from dark mode palettes.

## Contra
While OSC 10 & 11 are supported by xterm (and compatible terminals), and the documentation talks about "VT100 text foreground color", there is no guarantee things will work with dumber terminals.

## Pull Request
The proposal is implemented in PR #237

[^1]: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Operating-System-Commands
[^2]: https://alienryderflex.com/hsp.html

**Comment by jquast** [comment]
Yes I like it very much thanks for your time, we will definitely merge it for release

**Comment by jquast** [comment]
closed this was in the 1.20.0 release, thanks again @stefanholek you're the best
