### ISSUE TITLE
Examples of segregating terminal output

### ISSUE THREAD

**Issue by ajgringo619** [jquast/blessed#241]
I am trying to completely remove any curses modules/code from my programs, and hope I've come to the right place. The main questions are:

   1) Is **blessed** a complete rapper for **curses**?
   2) If so, are there examples of how to create sub-windows, like _curses.newwin_?

I'm trying to create a database monitor that prints out pandas dataframes in separate areas of the screen. For now, I'm converting the dataframes to multi-line strings, then printing each line with _term.move_xy_ commands.

**Comment by avylove** [comment]
Blessed is not a complete wrapper for curses. It does not have any abstraction for Curses windows. Blessed is primarily for colors, formating, keyboard input, cursor location, and other functionality provided through terminal escape codes. Some people do use Blessed along with Curses windows. You may want to look at the examples in the Readme and explore those projects if you see something similar to what you're trying to do.

**Comment by ajgringo619** [comment]
OK, thanks for the detailed info.
