### ISSUE TITLE
Arrow key input not working

### ISSUE THREAD

**Issue by tobyMickelson** [jquast/blessed#246]
When using `with term.cbrake():`, I am unable to get usable input. It starts by not accepting input then thinks every input is `KEY_LEFT`.

Here is what I tested arrow key input with:
```python
from blessed import Terminal

term = Terminal()
print(f"{term.home}{term.black_on_skyblue}{term.clear}")


with term.cbrake():
    inp = term.inkey()
    while term.inkey() != 'q':
        if inp.name == "KEY_LEFT":
            print("You pressed left")
```
I also tested it with `term.raw()`

System information:
MacOS Monterey 12.6.1 (21G217)
Python 3.10.5 (v3.10.5:f377153967, Jun  6 2022, 12:36:10) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin

**Comment by jquast** [comment]
try this instead,

```python
from blessed import Terminal

term = Terminal()
print(f"{term.home}{term.black_on_skyblue}{term.clear}")


with term.cbrake():
    while True:
       inp = term.inkey()
       if inp.name == "KEY_LEFT":
            print("You pressed left")
```

the `inp` variable was never re-assigned after the first key is pressed, so it was always displaying the first key that was pressed

**Comment by tobyMickelson** [comment]
Thanks for the help, but now it only works with raw but not cbrake.

**Comment by tobyMickelson** [comment]
Thank you for helping fix my stupid typo.
