### ISSUE TITLE
Text direction?

### ISSUE THREAD

**Issue by hearlambeth** [jquast/blessed#249]
Hiya,

Thanks for this wonderful library. This might be a feature request or something I'm missing: does Terminal have text direction? The default is of course horizontal, but I'm wondering about printing vertically, even at diagonal/arbitrary angles.

`output`
`u`
`t`
`p`
`u`
`t`

This wouldn't be hard for me to code for my own implementation but I'm wondering if it's already here. I'm not seeing it in curses.

Not submitting a pull request as I'm not capable enough as a coder.

Thanks,
Paul

**Comment by jquast** [comment]
There is not anything for vertical or diagonal text, you will probably want to use [move_xy()](https://blessed.readthedocs.io/en/latest/location.html#location)

There is such a thing as [Right-to-left unicode](https://en.wikipedia.org/wiki/Left-to-right_mark) mark, but at least in my terminal, it has no effect, though I sometimes enable it by accident in a web browser (Command+Shift+X in Firefox on osx) and confuse myself.

Enjoy your project!

**Comment by hearlambeth** [comment]
Thanks so much for the fast response!

Had no idea there was a shortcut for that. Ctrl+shift+x works in Firefox in Windows too.
