### ISSUE TITLE
Features from Curtsies that could belong in Blessed

### ISSUE THREAD

**Issue by thomasballinger** [jquast/blessed#26]
I work on [a library](https://github.com/thomasballinger/curtsies) that currently duplicates functionality from Blessed. I'd like to use Blessed for a lot of things instead of having my own implementations, but am curious about whether you'd want any of these features in Blessed. Would any of the following belong in Blessed?

* Colored strings that don't format themselves until they're finally rendered (see http://curtsies.readthedocs.org/en/latest/index.html#fmtstr-rationale)
* A 2d array of styled characters for rendering to the screen
* A caching screen renderer (renders only portions of the screen necessary assuming no other writes to stdout have occurred)
* Querying cursor position (I'm confused about whether https://github.com/jquast/blessed/issues/19 is talking about this or something else)
* Changes to the keypress detector: using a [reactor](https://github.com/thomasballinger/curtsies/blob/master/curtsies/input.py#L38) for scheduling events while reading on stdin, being interruptible by signals and messages from other threads

I imagine these *don't* belong in Blessed, but wanted to see what you thought.

**Comment by jquast** [comment]
Closing this issue with some final thoughts:

Lazy rendering
--------------------

Duplicating the ``initscr()`` round of functions in curses is beyond the scope of Blessed. Very much of what is discussed in these first two points are relative to such features in the curses library (such as lazy painting).

On FmtStr
--------------

We wish very much return only Unicode strings, to have deterministic output given input, and a limited amount of state.  As for combining, Please see #61 which enables nested styling.


On querying cursor position
-------------------------------------

Yes, will merge soon.

On UI
--------

such as readline, dialog boxes, progress bars, and other fun.


Blessed is *only* a very thin and simple to use API abstraction layer above curses, providing a pythonic interface over really, only, the simplest of sequence emission and parsing that curses provide. As an example, Blessed as an API is comparable to its matching graphical API's provided by the Linux Framebuffer or OpenGL: low-level pixel-pushing kind of libraries.
To ensure scope is limited, blessed will not attempt to solve abstractions of curses that would occur after ``initscr()``, or any facsimile UI interfaces.  This is important to ensure it is a "core" dependency of any upper layer API's that are welcome to provide such interfaces.

On keyboard callbacks/event loops
-----------------------------------------------

[Currently, blessed provides a perfectly functional API for those wishing to use an asyncio event loop -- and this is very much the purpose of the design of python 3.4 asyncio: to allow asynchronous I/O by without enforcing a particular event looping paradigm.

I have not yet provided an example of blessed used with asyncio in the bin/ folder -- we need to find an asyncio project to integrate with and so. An example I have written using stdin as a polling callback: https://github.com/jquast/telnetlib3/blob/fd39251b7650f4834b43891b9a5020845dfa197e/bin/telnet-client#L59 -- such function could easily be replaced in curtsies or any other UI system with a call term.inkey(timeout=0), and methods such as ``getch`` and ``kbhit`` may be derived and modified to accomidate any event looping system you wish.  Enforcing a callback mechanism is out of scope, however.

asyncio can be instructed to perform a callback when a filedescriptor (stdin) is ready, which you could then author your own coroutine to poll term.inkey(timeout=0.0) -- which may be u'' if only a partial sequence was received up to this moment.

**Comment by thomasballinger** [comment]
Thanks for the event loop description, makes sense. With you 100% on unicode vs bytes.

Re: FmtStr strengths, the feature I was most excited about is being able to do geometry with them for layout, but I think FmtStr's approach to everything else isn't great. I hope to change FmtStrs to use Blessed strings for output instead of duplicating this, but to keep them around in Curtsies for layout math.
