### ISSUE TITLE
Terminal.length('\x1b[m') returns wrong length of 2.

### ISSUE THREAD

**Issue by haliphax** [jquast/blessed#45]
>>> from blessed import Terminal
    >>> term = Terminal()
    >>> text = u'\x1b[1m\x1b[30m13:55\x1b[m \x1b[1m\x1b[30m-\x1b[m\x1b[m\x1b[37m*\x1b[m\x1b[m\x1b[1m\x1b[30m-\x1b[m\x1b[m Use \x1b[1m/QUIT\x1b[m\x1b[m to quit. Other commands: \x1b[1m/HELP\x1b[m\x1b[m\x1b[37m, \x1b[m\x1b[m\x1b[1m/ME\x1b[m\x1b[m\x1b[37m, \x1b[m\x1b[m\x1b[1m/TOPIC\x1b[m\x1b[m\x1b[37m, \x1b[m\x1b[m\x1b[1m/NAMES\x1b[m\x1b[m\x1b[m'
    >>> term.wrap(text, 46)
    [u'\x1b[1m\x1b[30m13:55\x1b[m \x1b[1m\x1b[30m-\x1b[m\x1b[m\x1b[37m*\x1b[m\x1b[m\x1b[1m\x1b[30m-\x1b[m\x1b[m Use \x1b[1m/QUIT\x1b[m\x1b[m to quit.',
    u'Other commands: \x1b[1m/HELP\x1b[m\x1b[m\x1b[37m, \x1b[m\x1b[m\x1b[1m/ME\x1b[m\x1b[m\x1b[37m,',
    u'\x1b[m\x1b[m\x1b[1m/TOPIC\x1b[m\x1b[m\x1b[37m, \x1b[m\x1b[m\x1b[1m/NAMES\x1b[m\x1b[m\x1b[m']

I added line breaks for clarity in the output of `term.wrap()`. Here's what it winds up wrapping to:

    13:55 -*- Use /QUIT to quit.
    Other commands: /HELP, /ME,
    /TOPIC, /NAMES

The first line is 28 characters. Even by adding ' Other', it would only be 34 characters--well within the limit of 46 that I'm using in the example. The second line is 27 characters. By adding ' /TOPIC,', it would only be 32 characters--again, within the limit of 46.

I'm wondering if this is because the output is messy and has a lot of repeated `\x1b[1m` sequences...

**Comment by haliphax** [comment]
With the repeating `\x1b[1m` and `\x1b[m` omitted, it's better, but still inaccurate.

**Comment by jquast** [comment]
problem is due to ``'\x1b[m'`` determined to be length of 2.  Presumably, a ``'x1b['`` alone is also valid in some other context, maybe in error

**Comment by jquast** [comment]
Closed by a3f8881e6c9aa65be2f6835007d77e242658772f -- thanks !!
