### ISSUE TITLE
Hint at correct use of term.clear() in the README

### ISSUE THREAD

**Issue by S0lll0s** [jquast/blessed#51]
I'm creating a fullscreen GUI, this is my basic code:

    from blessed import Terminal

    term = Terminal()
    def main():
      while True:
        term.clear()
        term.move(0, 0)
        print("----")
        print("-##-")
        print("----")

        key = term.inkey()
        if key in ("q", "Q"):
          break

    with term.cbreak():
      with term.fullscreen():
        main()

but this doesn't work, it keeps writing below the last thing it printed instead of clearing the screen.

**Comment by S0lll0s** [comment]
Just realized I need to print the output - my bad. This could use a heads up in the readme though!
(Especially because there's no exampe)

**Comment by spacebiggles** [comment]
I made this mistake a bunch when I was getting started too. It would definitely be easier with a heads up.

**Comment by jquast** [comment]
In an upcoming branch merge, we have only a single 1 page introductory example that will be displayed as the github README and the pypi description: https://github.com/erikrose/blessings/blob/blessed-integration/docs/intro.rst

If you can make any suggestions to this article in particular that would help, let us know

**Comment by jquast** [comment]
Perhaps some topic on how blessings is with few side-effects -- that calls to term.clear() is the return value of the string sequence that may be composed and written to stdout to clear the screen .. right up front, if helps
