### ISSUE TITLE
sphinx docfix: strange API docstring descriptions for constants

### ISSUE THREAD

**Issue by jquast** [jquast/blessed#80]
See example, http://blessed.readthedocs.org/en/latest/api.html#blessed.formatters.COMPOUNDABLES

which reads:

```

COMPOUNDABLES = {'bright_magenta', 'standout', 'bright_red', 'on_bright_magenta', 'bright_blue', 'magenta', 'bold', 'superscript', 'bright_white', 'on_bright_black', 'on_black', 'on_green', 'on_magenta', 'on_cyan', 'on_bright_yellow', 'green', 'on_white', 'on_bright_cyan', 'underline', 'italic', 'on_bright_blue', 'on_blue', 'dim', 'bright_black', 'bright_cyan', 'on_bright_red', 'blink', 'blue', 'yellow', 'bright_yellow', 'shadow', 'on_bright_green', 'on_red', 'black', 'subscript', 'white', 'on_yellow', 'red', 'on_bright_white', 'reverse', 'bright_green', 'cyan'}

    set() -> new empty set object set(iterable) -> new set object

    Build an unordered collection of unique elements.
```

We would rather describe the meaning of the data than the use of a `set` instance !

**Comment by avylove** [comment]
Same behavior for CURSES_KEYCODE_OVERRIDE_MIXIN and DEFAULT_SEQUENCE_MIXIN.

However, when I built this locally to work on it, the comments before the contents were used as the docstring. For example:

```
COMPOUNDABLES = {'black', 'blink', 'blue', 'bold', 'bright_black', 'bright_blue', 'bright_cyan', 'bright_green', 'bright_magenta', 'bright_red', 'bright_white', 'bright_yellow', 'cyan', 'dim', 'green', 'italic', 'magenta', 'on_black', 'on_blue', 'on_bright_black', 'on_bright_blue', 'on_bright_cyan', 'on_bright_green', 'on_bright_magenta', 'on_bright_red', 'on_bright_white', 'on_bright_yellow', 'on_cyan', 'on_green', 'on_magenta', 'on_red', 'on_white', 'on_yellow', 'red', 'reverse', 'shadow', 'standout', 'subscript', 'superscript', 'underline', 'white', 'yellow'}

    Attributes and colors which may be compounded by underscore.
```

This may just be a change to Sphinx. I tried to look at master on readthedocs, but it doesn't seem to be public. If you confirm the behavior for master, this could probably be closed at the next release.

**Comment by avylove** [comment]
I was looking at readthedocs and it seems like the last build was 2.5 years ago, and that failed. I had no issues building locally except having to install sphinx-paramlinks, which might require you to load it in a virtual environment, if that's not already configured. Otherwise, I'm not sure why builds aren't being triggered, but probably something with the github hooks or authentication.

**Comment by jquast** [comment]
I don't know why it wasn't kicking off automatically, I checked all the settings, I can't really recall if it ever worked, anyway I did it manually and that worked fine. also the docstring rendered better this time.

**Comment by avylove** [comment]
Awesome!

Does the webhook exist for the GitHub repo underder settings-> Webhooks? It may need to be created or updated. Either way it might be best to delete it if it exists and then go to ReadTheDocs for the project, Admin -> Integrations, and add a new webhook from there.

**Comment by jquast** [comment]
Ah that was it, thanks for the direction, the webhook had be re-created, it should work now thanks!
