### ISSUE TITLE
BUG: __version__ not present

### ISSUE THREAD

**Issue by norok2** [jquast/blessed#92]
Running:

```
import blessed
blessed.__version__
```

suggests that the `__version__` attribute is not defined in the `blessed` module, and it probably should. See: https://www.python.org/dev/peps/pep-0008/ and https://www.python.org/dev/peps/pep-0396/

**Comment by jquast** [comment]
Agreed, ok. Will.

**Comment by jquast** [comment]
``blessed.__version__`` is available in next release, ``1.14.2`` to be made later today, thank you again for your report @norok2 !

**Comment by norok2** [comment]
Thank you for maintaining this cool package!

**Comment by jquast** [comment]
happy to. glad you enjoy it, this is on pypi.
