### ISSUE TITLE
Terminal.get_location() coordinates do not match Terminal.move() coordinates

### ISSUE THREAD

**Issue by adampush** [jquast/blessed#94]
I'm using `blessed 1.14.1`. The x and y-values returned by `Terminal.get_location()` are one greater than the values needed for `Terminal.move()` to put the cursor at that location.

Example:

```python
import blessed

def move_and_report(row=0, col=0):
    term = blessed.Terminal()
    print(term.move(row, col), end='', flush=True)
    y, x = term.get_location()
    print('o <-- y, x: {}, {}'.format(y, x), end='', flush=True)
````

![blessed-get-location-bug2](https://cloud.githubusercontent.com/assets/16997823/22859890/61e01ce0-f0ba-11e6-9001-9f1056dbe79e.png)

`get_location` docstring indicates this is not the intended behavior:
```python
        """The ``(row, col)`` return value matches the parameter order of the
        ``move`` capability, so that the following sequence should cause the
        cursor to not move at all::
            >>> term = Terminal()
            >>> term.move(*term.get_location()))"""
```

Somewhat related to issue #65

**Comment by jquast** [comment]
Excellent report, thank you @adampush.

- `get_location()` should adjust the return values to be subtracted by one, so that they match the coordinate system of `move()`.

We should wish to have a single coordinate system, the `(0, 0)` values received naturally by the `move()` sequence is preferred

**Comment by jquast** [comment]
We can write a test case using pyte if we address the issue I just referenced above (pyte does not yet support this sequence)

**Comment by adampush** [comment]
Not sure if this is exactly appropriate to add here but, here goes...

Trying to set up a dev repo on my local machine to fix and write test case for this, but I'm running into a problem getting `tox` to run. It hangs on the following:

    about runtests: commands[3] | python /home/user/projects/blessed/bin/display-maxcanon.py
    auto-detecting MAX_CANON:

I have let it run for several minutes, does not appear to be progressing.

When I `control + C` to interrupt, the resulting traceback is:

```
Traceback (most recent call last):
  File "/home/user/projects/blessed/bin/display-maxcanon.py", line 80, in <module>
    detect_maxcanon()
  File "/home/user/projects/blessed/bin/display-maxcanon.py", line 64, in detect_maxcanon
    result = child.expect([ch_marker * blocksize, u'\a', pexpect.TIMEOUT])
  File "/home/user/projects/blessed/.tox/about/lib/python3.5/site-packages/pexpect/spawnbase.py", line 321, in expect
    timeout, searchwindowsize, async)
  File "/home/user/projects/blessed/.tox/about/lib/python3.5/site-packages/pexpect/spawnbase.py", line 345, in expect_list
    return exp.expect_loop(timeout)
  File "/home/user/projects/blessed/.tox/about/lib/python3.5/site-packages/pexpect/expect.py", line 101, in expect_loop
    time.sleep(self.spawn.delayafterread)
KeyboardInterrupt
```


Running in a virtualenv on a Xubuntu 16.04 LTS virtual machine on Windows 8.1 host.

I'm kind of new, so it could easily be something dumb that I am doing.

**Comment by jquast** [comment]
Sorry I missed this until now—this step of the test (display-max cannon) should be deleted or disabled. It was something of an experiment, at the time, build servers like Travis CI needed some experimentation to understand “just what kind of build environment are we under, here?”

**Comment by adampush** [comment]
OK thanks no problem. I've since nuked that computer setup and have become occupied with some other things so it may take me a while to come back to this.

**Comment by avylove** [comment]
It seems like the `%i` in `u6` is being ignored. According to [this](https://gist.github.com/ihodes/6583556#file-termtypes-ti-L159), if `%i` is present in the terminal, the values should be decremented. I'm not seeing anywhere in the code that's happening.

```
# The cursor position report (<u6>) string must contain two scanf(3)-style 
# %d format elements.  The first of these must correspond to the Y coordinate
# and the second to the %d.  If the string contains the sequence %i, it is
# taken as an instruction to decrement each value after reading it (this is
# the inverse sense from the cup string).  The typical CPR value is
# \E[%i%d;%dR (on VT100/ANSI/ECMA-48-compatible terminals).
```

**Comment by jquast** [comment]
I'm thinking of supplying a `move_yx` alias to `move`, and new function `move_xy` that we rather suggest in examples/docs.

**Comment by jquast** [comment]
thanks again @avylove, I've added to changelog
