### ISSUE TITLE
time.sleep between inkey() calls

### ISSUE THREAD

**Issue by setphen** [jquast/blessed#97]
I'm trying to limit the number of key inputs per second in my app.
my main loop is something like:
```
while true:
    time.sleep(0.1)
    key_value = term.inkey()
    #key_value logic stuff
```

If I press 2 keys at the same time, they both get processed, with a 0.1 second delay. I want to ignore any keypresses during the 0.1 second sleep. Is this possible?

**Comment by ja-jquast** [comment]
this is not the place for support, only bugs please

https://github.com/jquast/blessed#bugs-contributing-support
